name: Deploy Medusa Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js (if needed for build or Medusa commands)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Setup Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      # AWS Auth using GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      # Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./my-medusa-store/Terraform

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
        working-directory: ./my-medusa-store/Terraform

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan
        working-directory: ./my-medusa-store/Terraform
